// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: api_backend.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackendUserCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role     string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *BackendUserCreateRequest) Reset() {
	*x = BackendUserCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_backend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendUserCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendUserCreateRequest) ProtoMessage() {}

func (x *BackendUserCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_backend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendUserCreateRequest.ProtoReflect.Descriptor instead.
func (*BackendUserCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_backend_proto_rawDescGZIP(), []int{0}
}

func (x *BackendUserCreateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BackendUserCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackendUserCreateRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *BackendUserCreateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type BackendUserCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BackendUserCreateResponse) Reset() {
	*x = BackendUserCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_backend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendUserCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendUserCreateResponse) ProtoMessage() {}

func (x *BackendUserCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_backend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendUserCreateResponse.ProtoReflect.Descriptor instead.
func (*BackendUserCreateResponse) Descriptor() ([]byte, []int) {
	return file_api_backend_proto_rawDescGZIP(), []int{1}
}

func (x *BackendUserCreateResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BackendUserListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecPerPage *uint64                              `protobuf:"varint,1,opt,name=rec_per_page,json=recPerPage,proto3,oneof" json:"rec_per_page,omitempty"`
	PageNum    *uint64                              `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3,oneof" json:"page_num,omitempty"`
	Order      *BackendUserListRequest_SortingOrder `protobuf:"bytes,3,opt,name=order,proto3,oneof" json:"order,omitempty"`
}

func (x *BackendUserListRequest) Reset() {
	*x = BackendUserListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_backend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendUserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendUserListRequest) ProtoMessage() {}

func (x *BackendUserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_backend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendUserListRequest.ProtoReflect.Descriptor instead.
func (*BackendUserListRequest) Descriptor() ([]byte, []int) {
	return file_api_backend_proto_rawDescGZIP(), []int{2}
}

func (x *BackendUserListRequest) GetRecPerPage() uint64 {
	if x != nil && x.RecPerPage != nil {
		return *x.RecPerPage
	}
	return 0
}

func (x *BackendUserListRequest) GetPageNum() uint64 {
	if x != nil && x.PageNum != nil {
		return *x.PageNum
	}
	return 0
}

func (x *BackendUserListRequest) GetOrder() *BackendUserListRequest_SortingOrder {
	if x != nil {
		return x.Order
	}
	return nil
}

type BackendUserListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*BackendUserListResponse_User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *BackendUserListResponse) Reset() {
	*x = BackendUserListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_backend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendUserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendUserListResponse) ProtoMessage() {}

func (x *BackendUserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_backend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendUserListResponse.ProtoReflect.Descriptor instead.
func (*BackendUserListResponse) Descriptor() ([]byte, []int) {
	return file_api_backend_proto_rawDescGZIP(), []int{3}
}

func (x *BackendUserListResponse) GetUsers() []*BackendUserListResponse_User {
	if x != nil {
		return x.Users
	}
	return nil
}

type BackendUserUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email       string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role        string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Password    string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Oldpassword string `protobuf:"bytes,6,opt,name=oldpassword,proto3" json:"oldpassword,omitempty"`
}

func (x *BackendUserUpdateRequest) Reset() {
	*x = BackendUserUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_backend_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendUserUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendUserUpdateRequest) ProtoMessage() {}

func (x *BackendUserUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_backend_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendUserUpdateRequest.ProtoReflect.Descriptor instead.
func (*BackendUserUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_backend_proto_rawDescGZIP(), []int{4}
}

func (x *BackendUserUpdateRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BackendUserUpdateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BackendUserUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackendUserUpdateRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *BackendUserUpdateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *BackendUserUpdateRequest) GetOldpassword() string {
	if x != nil {
		return x.Oldpassword
	}
	return ""
}

type BackendUserUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BackendUserUpdateResponse) Reset() {
	*x = BackendUserUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_backend_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendUserUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendUserUpdateResponse) ProtoMessage() {}

func (x *BackendUserUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_backend_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendUserUpdateResponse.ProtoReflect.Descriptor instead.
func (*BackendUserUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_backend_proto_rawDescGZIP(), []int{5}
}

type BackendUserDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *BackendUserDeleteRequest) Reset() {
	*x = BackendUserDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_backend_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendUserDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendUserDeleteRequest) ProtoMessage() {}

func (x *BackendUserDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_backend_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendUserDeleteRequest.ProtoReflect.Descriptor instead.
func (*BackendUserDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_backend_proto_rawDescGZIP(), []int{6}
}

func (x *BackendUserDeleteRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BackendUserDeleteRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type BackendUserDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BackendUserDeleteResponse) Reset() {
	*x = BackendUserDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_backend_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendUserDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendUserDeleteResponse) ProtoMessage() {}

func (x *BackendUserDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_backend_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendUserDeleteResponse.ProtoReflect.Descriptor instead.
func (*BackendUserDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_backend_proto_rawDescGZIP(), []int{7}
}

type BackendUserGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BackendUserGetRequest) Reset() {
	*x = BackendUserGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_backend_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendUserGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendUserGetRequest) ProtoMessage() {}

func (x *BackendUserGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_backend_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendUserGetRequest.ProtoReflect.Descriptor instead.
func (*BackendUserGetRequest) Descriptor() ([]byte, []int) {
	return file_api_backend_proto_rawDescGZIP(), []int{8}
}

func (x *BackendUserGetRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BackendUserGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role  string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *BackendUserGetResponse) Reset() {
	*x = BackendUserGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_backend_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendUserGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendUserGetResponse) ProtoMessage() {}

func (x *BackendUserGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_backend_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendUserGetResponse.ProtoReflect.Descriptor instead.
func (*BackendUserGetResponse) Descriptor() ([]byte, []int) {
	return file_api_backend_proto_rawDescGZIP(), []int{9}
}

func (x *BackendUserGetResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BackendUserGetResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BackendUserGetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackendUserGetResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type BackendUsersAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role     string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *BackendUsersAddRequest) Reset() {
	*x = BackendUsersAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_backend_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendUsersAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendUsersAddRequest) ProtoMessage() {}

func (x *BackendUsersAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_backend_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendUsersAddRequest.ProtoReflect.Descriptor instead.
func (*BackendUsersAddRequest) Descriptor() ([]byte, []int) {
	return file_api_backend_proto_rawDescGZIP(), []int{10}
}

func (x *BackendUsersAddRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BackendUsersAddRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackendUsersAddRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *BackendUsersAddRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type BackendUsersAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BackendUsersAddResponse) Reset() {
	*x = BackendUsersAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_backend_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendUsersAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendUsersAddResponse) ProtoMessage() {}

func (x *BackendUsersAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_backend_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendUsersAddResponse.ProtoReflect.Descriptor instead.
func (*BackendUsersAddResponse) Descriptor() ([]byte, []int) {
	return file_api_backend_proto_rawDescGZIP(), []int{11}
}

func (x *BackendUsersAddResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BackendUserListRequest_SortingOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field      string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Descending bool   `protobuf:"varint,2,opt,name=descending,proto3" json:"descending,omitempty"`
}

func (x *BackendUserListRequest_SortingOrder) Reset() {
	*x = BackendUserListRequest_SortingOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_backend_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendUserListRequest_SortingOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendUserListRequest_SortingOrder) ProtoMessage() {}

func (x *BackendUserListRequest_SortingOrder) ProtoReflect() protoreflect.Message {
	mi := &file_api_backend_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendUserListRequest_SortingOrder.ProtoReflect.Descriptor instead.
func (*BackendUserListRequest_SortingOrder) Descriptor() ([]byte, []int) {
	return file_api_backend_proto_rawDescGZIP(), []int{2, 0}
}

func (x *BackendUserListRequest_SortingOrder) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *BackendUserListRequest_SortingOrder) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

type BackendUserListResponse_User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role  string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *BackendUserListResponse_User) Reset() {
	*x = BackendUserListResponse_User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_backend_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendUserListResponse_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendUserListResponse_User) ProtoMessage() {}

func (x *BackendUserListResponse_User) ProtoReflect() protoreflect.Message {
	mi := &file_api_backend_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendUserListResponse_User.ProtoReflect.Descriptor instead.
func (*BackendUserListResponse_User) Descriptor() ([]byte, []int) {
	return file_api_backend_proto_rawDescGZIP(), []int{3, 0}
}

func (x *BackendUserListResponse_User) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BackendUserListResponse_User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BackendUserListResponse_User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackendUserListResponse_User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_api_backend_proto protoreflect.FileDescriptor

var file_api_backend_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x16, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x76, 0x6c,
	0x64, 0x65, 0x6d, 0x2e, 0x68, 0x77, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x74, 0x0a, 0x18, 0x42, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22,
	0x2b, 0x0a, 0x19, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa5, 0x02, 0x0a,
	0x16, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x5f, 0x70,
	0x65, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52,
	0x0a, 0x72, 0x65, 0x63, 0x50, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1e,
	0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x48, 0x01, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x56,
	0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3b, 0x2e,
	0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x76, 0x6c, 0x64, 0x65, 0x6d, 0x2e, 0x68,
	0x77, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6f,
	0x72, 0x74, 0x69, 0x6e, 0x67, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x48, 0x02, 0x52, 0x05, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x1a, 0x44, 0x0a, 0x0c, 0x53, 0x6f, 0x72, 0x74, 0x69, 0x6e,
	0x67, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x64, 0x65, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x64, 0x65, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x0f, 0x0a, 0x0d,
	0x5f, 0x72, 0x65, 0x63, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x42, 0x0b, 0x0a,
	0x09, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x22, 0xbb, 0x01, 0x0a, 0x17, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4a, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x34, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x76, 0x6c, 0x64, 0x65, 0x6d,
	0x2e, 0x68, 0x77, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x1a, 0x54, 0x0a, 0x04,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x22, 0xa6, 0x01, 0x0a, 0x18, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73,
	0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x6c, 0x64,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6f, 0x6c, 0x64, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x42,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x46, 0x0a, 0x18, 0x42, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x22, 0x1b, 0x0a, 0x19, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x0a,
	0x15, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x66, 0x0a, 0x16, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f,
	0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x72,
	0x0a, 0x16, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0x29, 0x0a, 0x17, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x32, 0xb6, 0x05,
	0x0a, 0x07, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12, 0x73, 0x0a, 0x0a, 0x55, 0x73, 0x65,
	0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x30, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x64,
	0x65, 0x76, 0x2e, 0x76, 0x6c, 0x64, 0x65, 0x6d, 0x2e, 0x68, 0x77, 0x32, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e,
	0x2e, 0x64, 0x65, 0x76, 0x2e, 0x76, 0x6c, 0x64, 0x65, 0x6d, 0x2e, 0x68, 0x77, 0x32, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6a,
	0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65, 0x74, 0x12, 0x2d, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e,
	0x2e, 0x64, 0x65, 0x76, 0x2e, 0x76, 0x6c, 0x64, 0x65, 0x6d, 0x2e, 0x68, 0x77, 0x32, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e,
	0x64, 0x65, 0x76, 0x2e, 0x76, 0x6c, 0x64, 0x65, 0x6d, 0x2e, 0x68, 0x77, 0x32, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6d, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2e, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x64, 0x65,
	0x76, 0x2e, 0x76, 0x6c, 0x64, 0x65, 0x6d, 0x2e, 0x68, 0x77, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x64, 0x65,
	0x76, 0x2e, 0x76, 0x6c, 0x64, 0x65, 0x6d, 0x2e, 0x68, 0x77, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x73, 0x0a, 0x0a, 0x55, 0x73, 0x65,
	0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x30, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x64,
	0x65, 0x76, 0x2e, 0x76, 0x6c, 0x64, 0x65, 0x6d, 0x2e, 0x68, 0x77, 0x32, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e,
	0x2e, 0x64, 0x65, 0x76, 0x2e, 0x76, 0x6c, 0x64, 0x65, 0x6d, 0x2e, 0x68, 0x77, 0x32, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x73,
	0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x30, 0x2e, 0x6f,
	0x7a, 0x6f, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x76, 0x6c, 0x64, 0x65, 0x6d, 0x2e, 0x68, 0x77,
	0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31,
	0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x76, 0x6c, 0x64, 0x65, 0x6d, 0x2e,
	0x68, 0x77, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x71, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x73, 0x41, 0x64, 0x64, 0x12,
	0x2e, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x76, 0x6c, 0x64, 0x65, 0x6d,
	0x2e, 0x68, 0x77, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2f, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x76, 0x6c, 0x64, 0x65, 0x6d,
	0x2e, 0x68, 0x77, 0x32, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62,
	0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x76, 0x6c, 0x64, 0x65, 0x6d, 0x2f,
	0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x31, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70,
	0x69, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_backend_proto_rawDescOnce sync.Once
	file_api_backend_proto_rawDescData = file_api_backend_proto_rawDesc
)

func file_api_backend_proto_rawDescGZIP() []byte {
	file_api_backend_proto_rawDescOnce.Do(func() {
		file_api_backend_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_backend_proto_rawDescData)
	})
	return file_api_backend_proto_rawDescData
}

var file_api_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_backend_proto_goTypes = []interface{}{
	(*BackendUserCreateRequest)(nil),            // 0: ozon.dev.vldem.hw2.api.BackendUserCreateRequest
	(*BackendUserCreateResponse)(nil),           // 1: ozon.dev.vldem.hw2.api.BackendUserCreateResponse
	(*BackendUserListRequest)(nil),              // 2: ozon.dev.vldem.hw2.api.BackendUserListRequest
	(*BackendUserListResponse)(nil),             // 3: ozon.dev.vldem.hw2.api.BackendUserListResponse
	(*BackendUserUpdateRequest)(nil),            // 4: ozon.dev.vldem.hw2.api.BackendUserUpdateRequest
	(*BackendUserUpdateResponse)(nil),           // 5: ozon.dev.vldem.hw2.api.BackendUserUpdateResponse
	(*BackendUserDeleteRequest)(nil),            // 6: ozon.dev.vldem.hw2.api.BackendUserDeleteRequest
	(*BackendUserDeleteResponse)(nil),           // 7: ozon.dev.vldem.hw2.api.BackendUserDeleteResponse
	(*BackendUserGetRequest)(nil),               // 8: ozon.dev.vldem.hw2.api.BackendUserGetRequest
	(*BackendUserGetResponse)(nil),              // 9: ozon.dev.vldem.hw2.api.BackendUserGetResponse
	(*BackendUsersAddRequest)(nil),              // 10: ozon.dev.vldem.hw2.api.BackendUsersAddRequest
	(*BackendUsersAddResponse)(nil),             // 11: ozon.dev.vldem.hw2.api.BackendUsersAddResponse
	(*BackendUserListRequest_SortingOrder)(nil), // 12: ozon.dev.vldem.hw2.api.BackendUserListRequest.SortingOrder
	(*BackendUserListResponse_User)(nil),        // 13: ozon.dev.vldem.hw2.api.BackendUserListResponse.User
}
var file_api_backend_proto_depIdxs = []int32{
	12, // 0: ozon.dev.vldem.hw2.api.BackendUserListRequest.order:type_name -> ozon.dev.vldem.hw2.api.BackendUserListRequest.SortingOrder
	13, // 1: ozon.dev.vldem.hw2.api.BackendUserListResponse.users:type_name -> ozon.dev.vldem.hw2.api.BackendUserListResponse.User
	0,  // 2: ozon.dev.vldem.hw2.api.Backend.UserCreate:input_type -> ozon.dev.vldem.hw2.api.BackendUserCreateRequest
	8,  // 3: ozon.dev.vldem.hw2.api.Backend.UserGet:input_type -> ozon.dev.vldem.hw2.api.BackendUserGetRequest
	2,  // 4: ozon.dev.vldem.hw2.api.Backend.UserList:input_type -> ozon.dev.vldem.hw2.api.BackendUserListRequest
	4,  // 5: ozon.dev.vldem.hw2.api.Backend.UserUpdate:input_type -> ozon.dev.vldem.hw2.api.BackendUserUpdateRequest
	6,  // 6: ozon.dev.vldem.hw2.api.Backend.UserDelete:input_type -> ozon.dev.vldem.hw2.api.BackendUserDeleteRequest
	10, // 7: ozon.dev.vldem.hw2.api.Backend.UsersAdd:input_type -> ozon.dev.vldem.hw2.api.BackendUsersAddRequest
	1,  // 8: ozon.dev.vldem.hw2.api.Backend.UserCreate:output_type -> ozon.dev.vldem.hw2.api.BackendUserCreateResponse
	9,  // 9: ozon.dev.vldem.hw2.api.Backend.UserGet:output_type -> ozon.dev.vldem.hw2.api.BackendUserGetResponse
	3,  // 10: ozon.dev.vldem.hw2.api.Backend.UserList:output_type -> ozon.dev.vldem.hw2.api.BackendUserListResponse
	5,  // 11: ozon.dev.vldem.hw2.api.Backend.UserUpdate:output_type -> ozon.dev.vldem.hw2.api.BackendUserUpdateResponse
	7,  // 12: ozon.dev.vldem.hw2.api.Backend.UserDelete:output_type -> ozon.dev.vldem.hw2.api.BackendUserDeleteResponse
	11, // 13: ozon.dev.vldem.hw2.api.Backend.UsersAdd:output_type -> ozon.dev.vldem.hw2.api.BackendUsersAddResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_backend_proto_init() }
func file_api_backend_proto_init() {
	if File_api_backend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_backend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendUserCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_backend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendUserCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_backend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendUserListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_backend_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendUserListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_backend_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendUserUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_backend_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendUserUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_backend_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendUserDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_backend_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendUserDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_backend_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendUserGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_backend_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendUserGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_backend_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendUsersAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_backend_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendUsersAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_backend_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendUserListRequest_SortingOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_backend_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendUserListResponse_User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_backend_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_backend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_backend_proto_goTypes,
		DependencyIndexes: file_api_backend_proto_depIdxs,
		MessageInfos:      file_api_backend_proto_msgTypes,
	}.Build()
	File_api_backend_proto = out.File
	file_api_backend_proto_rawDesc = nil
	file_api_backend_proto_goTypes = nil
	file_api_backend_proto_depIdxs = nil
}
