// Code generated by MockGen. DO NOT EDIT.
// Source: ./utils.go

// Package mock_utils is a generated GoMock package.
package mock_utils

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUtilsInterface is a mock of UtilsInterface interface.
type MockUtilsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUtilsInterfaceMockRecorder
}

// MockUtilsInterfaceMockRecorder is the mock recorder for MockUtilsInterface.
type MockUtilsInterfaceMockRecorder struct {
	mock *MockUtilsInterface
}

// NewMockUtilsInterface creates a new mock instance.
func NewMockUtilsInterface(ctrl *gomock.Controller) *MockUtilsInterface {
	mock := &MockUtilsInterface{ctrl: ctrl}
	mock.recorder = &MockUtilsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUtilsInterface) EXPECT() *MockUtilsInterfaceMockRecorder {
	return m.recorder
}

// GetRandIdString mocks base method.
func (m *MockUtilsInterface) GetRandIdString(length int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandIdString", length)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRandIdString indicates an expected call of GetRandIdString.
func (mr *MockUtilsInterfaceMockRecorder) GetRandIdString(length interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandIdString", reflect.TypeOf((*MockUtilsInterface)(nil).GetRandIdString), length)
}
