version: "2"
services:
  zk1:
    image: confluentinc/cp-zookeeper:5.4.3
    ports:
      - "22181:22181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk1:22888:23888;zk2:32888:33888;zk3:42888:43888

  zk2:
    image: confluentinc/cp-zookeeper:5.4.3
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk1:22888:23888;zk2:32888:33888;zk3:42888:43888

  zk3:
    image: confluentinc/cp-zookeeper:5.4.3
    ports:
      - "42181:42181"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk1:22888:23888;zk2:32888:33888;zk3:42888:43888

  kafka-1:
    image: confluentinc/cp-kafka:5.4.3
    ports:
      - "19092:19092"
      - "19091:19091"
    depends_on:
      - zk1
      - zk2
      - zk3
    environment:
      KAFKA_CLUSTER_ID: test-kafka-cluster
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk1:22181,zk2:32181,zk3:42181
      KAFKA_LISTENERS: LISTENER_INTERNAL://kafka-1:19092,LISTENER_EXTERNAL://kafka-1:19091
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka-1:19092,LISTENER_EXTERNAL://localhost:19091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL

  kafka-2:
    image: confluentinc/cp-kafka:5.4.3
    ports:
      - "29092:29092"
      - "29091:29091"
    depends_on:
      - zk1
      - zk2
      - zk3
    environment:
      KAFKA_CLUSTER_ID: test-kafka-cluster
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zk1:22181,zk2:32181,zk3:42181
      KAFKA_LISTENERS: LISTENER_INTERNAL://kafka-2:19092,LISTENER_EXTERNAL://kafka-2:29091
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka-2:19092,LISTENER_EXTERNAL://localhost:29091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL

  kafka-3:
    image: confluentinc/cp-kafka:5.4.3
    ports:
      - "39092:39092"
      - "39091:39091"
    depends_on:
      - zk1
      - zk2
      - zk3
    environment:
      KAFKA_CLUSTER_ID: test-kafka-cluster
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zk1:22181,zk2:32181,zk3:42181
      KAFKA_LISTENERS: LISTENER_INTERNAL://kafka-3:19092,LISTENER_EXTERNAL://kafka-3:39091
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka-3:19092,LISTENER_EXTERNAL://localhost:39091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - "8080:8080"
    restart: "no"
    environment:
      KAFKA_CLUSTERS_0_NAME: test-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:19092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zk1:22181
#      KAFKA_CLUSTERS_0_READONLY: true

# version: "3"

# services:
#   kafka-ui:
#     image: provectuslabs/kafka-ui:latest
#     ports:
#       - "8080:8080"
#     depends_on:
#       - kafka-2
#     environment:
#       - KAFKA_CLUSTERS_0_NAME=local
#       - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092,kafka-2:9092
#       - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

#   zookeeper:
#     image: zookeeper
#     ports:
#       - "2181:2181"
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181

#   kafka-1:
#     image: wurstmeister/kafka:latest
#     ports:
#       - "9095:9094"
#     depends_on:
#       - zookeeper
#     environment:
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

#       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#       KAFKA_LISTENERS: INTERNAL://kafka-1:9092,OUTSIDE://kafka-1:9094
#       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,OUTSIDE://localhost:9095
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT

#       KAFKA_LOG_DIRS: /kafka/logs
#       KAFKA_BROKER_ID: 500
#       KAFKA_offsets_topic_replication_factor: 3
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - ./kafka_data/500:/kafka

#   kafka-2:
#     image: wurstmeister/kafka:latest
#     ports:
#       - "9096:9094"
#     depends_on:
#       - kafka-1
#     environment:
#       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_LISTENERS: INTERNAL://kafka-2:9092,OUTSIDE://kafka-2:9094
#       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9092,OUTSIDE://localhost:9096
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
#       KAFKA_LOG_DIRS: /kafka/logs
#       KAFKA_BROKER_ID: 501
#       KAFKA_offsets_topic_replication_factor: 3
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - ./kafka_data/501:/kafka

# kafka-3:
#   image: wurstmeister/kafka
#   ports:
#     - "9097:9094"
#   environment:
#     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#     KAFKA_LISTENERS: INTERNAL://kafka-3:9092,OUTSIDE://kafka-3:9094
#     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:9092,OUTSIDE://localhost:9097
#     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
#     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#     KAFKA_LOG_DIRS: /kafka/logs
#     KAFKA_BROKER_ID: 502
#     KAFKA_offsets_topic_replication_factor: 3
#   volumes:
#     - /var/run/docker.sock:/var/run/docker.sock
#     - ./kafka_data/502:/kafka
